parameters:
#    jobmagazine.example.class: BionicUniversity\SergeyVasko\JobmagazineBundle\Example

services:
#    jobmagazine.example:
#        class: %jobmagazine.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
